--quick tester until data is given
INSERT INTO TEAMS (NAME) VALUES ('STRIPES'), ('SOLIDS') ON CONFLICT DO NOTHING;

INSERT INTO MATCHES (MATCH_DATE, TEAM1_ID, TEAM2_ID, TEAM1_POINTS, TEAM2_POINTS)
SELECT CURRENT_DATE, T1.ID, T2.ID, 7, 4
FROM TEAMS T1, TEAMS T2
WHERE T1.NAME='STRIPES' AND T2.NAME='SOLIDS'
ON CONFLICT DO NOTHING;
