app = "bip"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"
  context = "."

[[services]]
  internal_port = 80
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
